"""customer api keys (una clave por consumidor con servicios permitidos)

Revision ID: 630bf84fe073
Revises: c1e3a5b7d9f0
Create Date: 2026-10-05 17:07:54.775871

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630bf84fe073'
down_revision: str | None = 'c1e3a5b7d9f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_api_key_key_id'), 'customer_api_key', ['key_id'], unique=True)
    op.create_table('customer_api_key_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['customer_api_key.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'service_id')
    )
    # Nota: el autogenerate también detectó una deriva de nombres de índice
    # preexistente (cert_* -> certification_*, recovery_code) ajena a esta
    # migración; se deja fuera a propósito para no mezclar cambios.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_api_key_service')
    op.drop_index(op.f('ix_customer_api_key_key_id'), table_name='customer_api_key')
    op.drop_table('customer_api_key')
    # ### end Alembic commands ###
